### PR TITLE
Delete all_features_version_10_no_visit_variant_pcd.yml

### PR DESCRIPTION
**Pull request by karafecho**
Deleting outdated file with incomplete search_term and limit values.

### CODE REVIEW

**Comment by hyi** [comment]
@karafecho I see you deleted the PCD all features file in this PR. Are you going to add a new updated PCD all features file? If so, could you add the updated file in this PR also so that a valid PCD all features file will always be present in the repo?

**Comment by karafecho** [comment]
Yes, I added the updated file to the same working branch and included the following comment:

Adding updated all_features pcd YAML file with complete search_term and limit and without enum &id values. To create this file, I: (1) pulled all_features_version_10_no_visit_variant_pcd.yml from ground-truth-yaml-files folder within icees-api-config repo; (2) added search_term and limit to all PCD-specific variables; (3) replaced all asthma variables with those in all_features_version_10_no_visit_variant_asthma.yml, also within ground-truth-yaml files folder; and (4) removed all enum &id values. Hong fixed several formatting issues and validated the file.

Please let me know if I did something incorrectly.

**Comment by hyi** [comment]
@karafecho It looks good except there are two patient keys at the root level for this updated all features pcd file. See more details for the question from @maximusunc on slack. The original all features pcd file only has one patient key at the root level on the first line, so most likely the second root level patient key and values should be removed or something?

**Comment by karafecho** [comment]
Okay, I think I fixed this.

**Review by hyi — APPROVED** [review]

**Review by maximusunc — CHANGES_REQUESTED** [review]
See comment I left on search term issues

**Comment by karafecho** [comment]
Found two errors in all_features pcd YAML file while creating FHIR_mappings pcd YAML file. Removed old file and added corrected file. @maximusunc : perhaps you can take a look?

**Review by maximusunc — APPROVED** [review]

**Pull request merged**
